### ISSUE TITLE
example doesn't compile

### ISSUE THREAD

**Issue by jeberly** [ory-am/fosite#27]
While trying to run the example on your readme, I get the following:

```
go install github.com/ory-am/fosite/fosite-example
# github.com/ory-am/fosite/enigma
../../go/src/github.com/ory-am/fosite/enigma/hmacsha.go:26: base64.StdEncoding.WithPadding undefined (type *base64.Encoding has no field or method WithPadding)
../../go/src/github.com/ory-am/fosite/enigma/hmacsha.go:26: undefined: base64.NoPadding
```

Any ideas?

**Comment by arekkas** [comment]
Yes, looks like you're using Go <= 1.4. Unfortunately, fosite currently only works with 1.5 or greater but I gladly accept any PRs granting compability with older Go versions.

**Comment by jeberly** [comment]
Thanks for quick response! Ok, we will prob. be upgrading soon anyway.

**Comment by arekkas** [comment]
I think base64 padding is the only thing that is causing older builds to fail. Not sure if there is a way to achieve the same thing (base64 without padding) with older versions of Go. But seeing how Go progresses on garbage collection and awesomeness it is probably a good idea to upgrade anyways :)

**Comment by arekkas** [comment]
Found something on stackoverflow which might help: http://stackoverflow.com/questions/31971614/base64-encode-decode-without-padding-on-golang-appengine

**Comment by jeberly** [comment]
You are fast, thanks!  I know this is not the place to ask, but do you consider this ready for use in production?

**Comment by arekkas** [comment]
Difficult to say, the example shows that the [public facing API](https://github.com/ory-am/fosite/blob/master/oauth2.go) is pretty stable. I want to implement fosite in [hydra](https://github.com/ory-am/hydra) which will be used in production. I also want to implement OpenID Connect. Both of these things might need some refactoring of internal methods.

If you need 100% API stability I'd suggest to wait until fosite is released via [gopkg.in as v1](https://github.com/ory-am/fosite#installation). If you're okay with using [godep](https://github.com/tools/godep) and fixing a few things when BC breaks arise I'd say you're good to go.

In terms of security, I'd say that fosite is already more stable and more secure than other golang oauth2 frameworks.

**Comment by arekkas** [comment]
One more thing: I haven't imeplemented a real storage (e.g. against mysql/postgres/...) yet, only an in-memory storage. This might also be an an area which needs a little refactoring, depending on the limitations of the different DBALs.
